baseURL: "https://wrhamxyz.github.io/"
title: Wrham's dump
paginate: 5
theme: "PaperMod"

params:
  defaultTheme: auto
  profileMode:
    enabled: true
    title: "Wrham"
    subtitle: "Hello folks, my name is wrham, i love memes or something xd"
    imageUrl: "https://i.imgur.com/5VXxDzz.png"
    imageTitle: "pfp"
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: Archive
        url: "/archives"
  
  ShowShareButtons: false
  ShowReadingTime: true
  ShowToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  editPost:
    URL: "https://github.com/wrhamxyz.github.io/tree/master/content"
    Text: "Suggest Changes"
    appendFilePath: true
  
  socialIcons:
    - name: "github"
      url: "https://github.com/wrhamxyz"
    - name: "reddit"
      url: "https://www.reddit.com/u/aerospace360"

menu:
  main:
    - name: Archive
      url: archives
      weight: 10
    - name: Tags
      url: tags
      weight: 10
    - name: Search
      url: search
      weight: 10
    - name: Categories
      url: categories
      weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

