baseURL = "https://warofzen.is-a.dev"
theme = "risotto"
title = "Hamm's site"
author = "Warofzen"
copyright = "© some rights reserved"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
# sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "warofzen"
description = "A simple man making his way through the internet."
# unicodemoji logo:
logo = "🌌"
# or use an image:
#logo_image = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/warofzen"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:warofzen1@proton.me"

[[params.socialLinks]]
icon = "fa-brands fa-discord"
title = "Discord"
url = "https://discord.com/users/713687221244264468"

[menu]

  # [[menu.about]]
  #   identifier = "about"
  #   name = "about"
  #   url = "/"
  #   weight = 100

  [[menu.main]]
    identifier = "contact"
    name = "contact"
    url = "/contact"
    weight = 90

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = 80

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
